spring.application.name=ms-bff-web

server.port=${PORT:8096}

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
eureka.instance.ip-address=127.0.0.1

management.endpoints.web.exposure.include=health,info,circuitbreakers

spring.threads.virtual.enabled=true

server.tomcat.threads.max=500