
# PUERTO
server.port=${PORT:8084}

spring.application.name=${APP_NAME:msenvio}

# DATABASE
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:ms_envio}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASS:root}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=ms-envio-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer

spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.use.type.headers=false

spring.kafka.consumer.properties.spring.json.value.default.type=seb.com.msenvio.infrastructure.adapter.in.kafka.dto.pedido.PedidoPreparadoEventDto


spring.kafka.consumer.properties.spring.json.trusted.packages=*
